Feature/safety and side effects page
HackMort/koselugo pull request #36
Opened 2023-03-28 22:32 UTC by elian-dev

The safety and side effects page created, mobile, desktop and tablet.

2023-03-28 23:04 UTC, HackMort requested changes
Please make sure you fix & test everything before sending yout PR again. There are a lot of styles and spacing issues.

2023-03-28 23:04 UTC, HackMort commented on src/pages/safety-&-side-effects.astro
> +            <img src="/assets/images/safety-and-side-effects/side-effects-icon.png" alt=" " srcset="">
- Image does not need to have a fixed height, you should only need to set the width. You also need flex: 1; to maintain the aspect ratio if you use it as a direct child of a element with flex.
- Image margin-bottom should be 33px not 10px

2023-03-28 23:04 UTC, HackMort commented on src/pages/safety-&-side-effects.astro
> +          <h3>Koselugo may cause serious side effects, including:</h3>
- I'm not sure why you need a fixed margin on this heading, it makes it looks out of place compared to the rest of the content on mobile.
- Please add classes and use the classes of the elements, when the SEO kit arrives, we may need to change this to a different heading or tag and we are gonna lose the styles because it is not an h3 anymore.

2023-03-28 23:04 UTC, HackMort commented on src/pages/safety-&-side-effects.astro
> +          <ul class="side-effects-page--list">
- Please check all the spacing on all these lists and paragraphs of text. Fix them based on the spacing between them in the figma.

2023-03-28 23:04 UTC, HackMort commented on src/pages/safety-&-side-effects.astro
> +          <h3>
- Similar to my previous heading comment, please refer to figma, there are some margin that you don't need.

2023-03-28 23:04 UTC, HackMort commented on src/pages/safety-&-side-effects.astro
> +          <h3>The most common side effects of Koselugo are:</h3>
- Similar to my previous heading comment, please refer to figma, there are some margin that you don't need.

2023-03-28 23:04 UTC, HackMort commented on src/pages/safety-&-side-effects.astro
> +                <img src="/assets/images/safety-and-side-effects/icons/tiredness-feeling-icon.png" alt="" srcset=""><span class="side-effects-page--commun-list__point desktop--only"></span>Feeling of
- Text should be centered on mobile.

2023-03-28 23:04 UTC, HackMort commented on src/pages/safety-&-side-effects.astro
> +                <img src="/assets/images/safety-and-side-effects/icons/itching-icon.png" alt="" srcset=""><span class="side-effects-page--commun-list__point desktop--only"></span>Itching
There should be more space between this text and the next section. Please check the figma for the corresponding values.

2023-03-28 23:04 UTC, HackMort commented on src/pages/safety-&-side-effects.astro
> +          <h3>These are not all the possible side effects of Koselugo</h3>
Same as previous heading feedback

2023-03-28 23:04 UTC, HackMort commented on src/pages/safety-&-side-effects.astro
> +          <p>
It needs to have more space above.

2023-03-28 23:04 UTC, HackMort commented on src/pages/safety-&-side-effects.astro
> +          Remember, the information on this page does not replace medical guidance or directions from your doctor. Always talk to them about side effects and ways to manage them.
The padding for this box does not match the spacing in the figma.

2023-03-28 23:04 UTC, HackMort commented on src/pages/safety-&-side-effects.astro
> +          <div class="side-effects-page--steps">
Please match the space above for this graphic

2023-03-28 23:04 UTC, HackMort commented on src/pages/safety-&-side-effects.astro
> +          <h3 class="text--center">Your child will take 3 tests before starting Koselugo:</h3>
Same comments for previous headings.

2023-03-28 23:04 UTC, HackMort commented on src/pages/safety-&-side-effects.astro
> +
Missing heading here.

2023-03-28 23:04 UTC, HackMort commented on src/pages/safety-&-side-effects.astro
> +            <h4 class="text--center">Have heart problems</h4>
Heading not matchin styles from figma.

2023-03-28 23:04 UTC, HackMort commented on src/pages/safety-&-side-effects.astro
> +            <h4 class="text--center">Have eye problems</h4>
Heading not matchin styles from figma.

2023-03-28 23:04 UTC, HackMort commented on src/pages/safety-&-side-effects.astro
> +              <h4 class="text--center">Are pregnant or plan to become pregnant. Koselugo can harm an unborn baby</h4>
Heading not matchin styles from figma.

2023-03-28 23:04 UTC, HackMort commented on src/pages/safety-&-side-effects.astro
> +              <h4 class="text--center">Are breastfeeding or plan to breastfeed</h4>
Heading not matchin styles from figma.

2023-03-28 23:04 UTC, HackMort commented on src/pages/safety-&-side-effects.astro
> +          Review the treatment journey of patients who took Koselugo in a clinical study
Review styles and spacing of this text.

2023-03-28 23:04 UTC, HackMort commented on src/pages/safety-&-side-effects.astro
> +        <a href="" class="text--center color--rose">See their journeys here</a>
Do not leave anchors href empty, look in the figma for the proper link, if there's not, please at least add the # symbol.

2023-03-29 19:41 UTC, AndersonCastellon requested changes

2023-03-29 19:41 UTC, AndersonCastellon commented on src/styles/style.scss
> +  line-height: 26px;
Why this change?
![image](https://user-images.githubusercontent.com/31933833/228616555-715c11e0-f9ad-487a-acbf-27028b88aa5c.png)

In mobile, the line height for paragraphs is 22.86px

2023-03-29 19:41 UTC, AndersonCastellon commented on src/pages/safety-&-side-effects.astro
> +          <h3 class="side-effects-page--section__heading side-effects-page--section__heading__3">
This h should  have 18px font size in mobile
![image](https://user-images.githubusercontent.com/31933833/228620348-217c2a31-2511-4b2c-bd28-a4b1b319508d.png)

2023-03-29 19:41 UTC, AndersonCastellon commented on src/styles/style.scss
> +    font-size: 22px;
![image](https://user-images.githubusercontent.com/31933833/228620571-242df893-0e70-4b45-a62f-3ce28ad228f1.png)

2023-03-29 19:41 UTC, AndersonCastellon commented on src/pages/safety-&-side-effects.astro
> +                Feeling of tiredness, weakness, or lacking energy
![image](https://user-images.githubusercontent.com/31933833/228621556-f68aaf32-6cc3-43a4-a7c2-55bd45f5fa8b.png)

This text should be in two lines only in mobile version

2023-03-29 19:41 UTC, AndersonCastellon commented on src/pages/safety-&-side-effects.astro
> +          <h3 class="side-effects-page--section__heading side-effects-page--section__heading__3">These are not all the possible side effects of Koselugo</h3>
This should be 18px font size in mobile. Please review all headings in the page
![image](https://user-images.githubusercontent.com/31933833/228632930-264b2f0b-d753-4ea4-8545-32f442e48957.png)

2023-03-29 19:41 UTC, AndersonCastellon commented on src/styles/style.scss
> +  font-size: 22px;
This should be 18px font size

2023-03-29 19:41 UTC, AndersonCastellon commented on src/styles/style.scss
> +  border: 1px solid #404040; //This color is not in the variables.scss file
You should add new colors to _variables.scss

2023-03-29 19:41 UTC, AndersonCastellon commented on src/styles/style.scss
> +  padding: 39px 49px;
Please avoid using px, only use rem's

2023-03-29 19:41 UTC, AndersonCastellon commented on src/pages/safety-&-side-effects.astro
> +            <img src="/assets/images/safety-and-side-effects/steps-to-test.png" alt=" ">
Please build this section with html. 
In figma we can export the necessary assets, like this:
https://www.figma.com/file/c2RY4spMOvjNHDLD7VYrth/Koselugo.com?node-id=1584%3A19451&t=ZOElbXGYc7n47ngk-1 

In some viewport size this type of assets appear with a bad quality, Also the text
![image](https://user-images.githubusercontent.com/31933833/228645125-14aac9d6-dd94-42af-bb65-a26cbf9fa4d4.png)

2023-03-29 19:41 UTC, AndersonCastellon commented on src/pages/safety-&-side-effects.astro
> +                <img class="side-effects-page--commun-list__item__img" src="/assets/images/safety-and-side-effects/icons/vomiting-icon.png" alt=" " srcset="">
![image](https://user-images.githubusercontent.com/31933833/228646082-46811368-1448-4a76-a75a-8200a861a17f.png)

Dots appear too big

This es figma:
![image](https://user-images.githubusercontent.com/31933833/228646274-1611a1ab-c6f2-4492-abd6-f9b6c635710c.png)

2023-03-29 19:41 UTC, AndersonCastellon commented on src/pages/safety-&-side-effects.astro
> +      <section class="side-effects-page--secondary-section">
In tablet versions, this sections appears outside the section above.

## Site
![image](https://user-images.githubusercontent.com/31933833/228647154-274c4c27-2373-480c-84e0-bf943b2a9fa6.png)

## Figma
![image](https://user-images.githubusercontent.com/31933833/228647311-662fe346-1b7d-4680-a162-45bd4a0dae2d.png)

2023-03-29 19:41 UTC, AndersonCastellon commented on src/pages/safety-&-side-effects.astro
> +          <ul class="side-effects-page--list">
Please make a deep review for this section:
I found errors with font size, list element position, .etc
![image](https://user-images.githubusercontent.com/31933833/228647994-dba9ef50-8ebe-4b1a-8a5f-94c546aef6b5.png)

2023-03-29 19:41 UTC, AndersonCastellon commented on src/pages/safety-&-side-effects.astro
> +            <div class="side-effects-page--problems-section__long">
## Site
![image](https://user-images.githubusercontent.com/31933833/228648510-17e81466-a883-4612-979a-fae2fa3a9d04.png)

## Figma
![image](https://user-images.githubusercontent.com/31933833/228648595-c0fa115f-32f5-464c-a3ca-d68047e46ffc.png)

2023-03-30 19:55 UTC, AndersonCastellon approved these changes
Looks great

2023-03-30 19:59 UTC, HackMort approved these changes

2023-03-30 19:59 UTC, HackMort commented
This is the way to go Geordy!

2023-03-30 19:59 UTC, merged